# Generated by Django 4.1.3 on 2022-12-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_objectviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='restra_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
