# Generated by Django 4.1.3 on 2022-12-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_dish_shot_description_dishrating_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('PUREVEG', 'Pure Veg'), ('NONVEG', 'Non-Veg'), ('BOTH', 'Both')], default='VEG', max_length=10),
            preserve_default=False,
        ),
    ]
