# Generated by Django 4.1.3 on 2022-12-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_restaurant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='dishes_thumbnail/'),
        ),
    ]
