# Generated by Django 4.1.3 on 2022-12-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_dishrating_created_at_dishrating_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.TextField(),
        ),
    ]
