# Generated by Django 4.1.3 on 2022-12-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_tags_dish_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
