# Generated by Django 4.1.3 on 2022-12-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='restaurant.tag'),
        ),
    ]
