# Generated by Django 4.1.3 on 2022-12-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_restra_id_objectviewed_model_name_and_more'),
        ('restaurant', '0016_alter_dish_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritiesRestaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourate_restras', to='accounts.buyer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourate_restras', to='restaurant.restaurant')),
            ],
        ),
    ]
